# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
servers: 3
# minAvailable: 2

# Configuring the memory requests and limits will
# also configure the JVM heap size accordingly
resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 1
    memory: 4Gi
tickTimeMs: 2000
initTicks: 10
syncTicks: 5
clientCnxns: 60
snapRetain: 3
purgeHours: 1
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5
logLevel: "INFO"
security:
  enabled: false
  runAsUser: 1000
  fsGroup: 1000

image:
  repository: docker.io/zenko/zenko-zookeeper
  tag: 0.0.6
  pullPolicy: IfNotPresent

storage:
  data:
    size: 10Gi
    # storageClass: default
  log:
    size: 50Gi
    # storageClass: default

# Affinities to add to the worker pods.
# Useful if you prefer to run workers on non-spot instances, for example
affinity: {}
# nodeAffinity:
#   preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 50
#       preference:
#         matchExpressions:
#           - key: spot
#             operator: NotIn
#             values:
#               - "true"
